# Project Name: Aixt project, https://gitlab.com/fermarsan/aixt-project.git
# File Name: builtin.c.v
# Author: Farith Ochoa León, Felipe Cardozo Hernandez and Fernando Martínez Santa
# Date: 2024
# License: MIT

port = "ESP32-C3FH4" 
device = "WeAct-Studio"
board = "ESP32-C3FH4"
backend = "arduino"  

cc_linux =  "-o"
cc_windows =  "C:\\Users\\dell\\AppData\\Local\\Programs\\Arduino IDE"
cc_flags =   "-o"

path = "WeAct-Studio/ESP32-C3FH4"

fixed_size_arrays =  "true"
fixed_size_strings = "true" 

void = "void" 
bool = "bool" 

i8 =    "int8_t"  #"char"
i16 =   "int16_t"
int =   "int32_t"
i64 =   "int64_t"
isize = "int32_t"
int_literal = "int32_t"

u8 =    "uint8_t"
u16 =   "uint16_t"
u32 =   "uint32_t"
u64 =   "uint64_t"
usize = "uint32_t"

f32 = "float"
f64 = "=== NOT SUPPORTED ==="
float_literal = "float"

rune =  "char"
string = "char []"

mutex = "=== NOT SUPPORTED ==="

main_ret_type = "int"
main_params =   "void"   

api_modules = [
    "pin",
    "pwm",
    "uart",
    "time",
    "adc" ,
]

[aliases]
