# Project Name: Aixt, https://github.com/fermarsan/aixt.git
#  Author: Fernando M. Santa
#  Date: 2024
#  License: MIT
#
#  Description: Setup file for ESP32-DevKitC
port =    "ESP32-DevKitC"
board =   "ESP32-WROOM-32"
backend = "arduino"

cc_linux =   "arduino-cli"
cc_windows = "arduino-cli.exe"
cc_make_flags =   "compile -b esp32:esp32:esp32 -v --output-dir @{file_dir_name}/build"

api_paths = [
    "Espressif/ESP32-DevKitC",
    "Arduino/arduino-generic",
    "Arduino/arduino-generic-UART",
]

v_defines = [
]

inline_as_c_macro = true

string_default_len = 50

compiler_setup_path = "setup/arduino32.toml"