# Project Name: Aixt, https://github.com/fermarsan/aixt.git
# Authors: 
#   - Fernado Martinez Santa
#   - Luis Alfredo Pinto Medina
# Date: 2024
# License: MIT
#
# Description: Setup file for the PIC16F8x port. 
port =      "PIC16F8x"
board =     "---"
backend =   "c"

cc_linux =   ""             # this port works by a Makefile
cc_windows = ""
cc_flags =   ""
cc_output_flag = ""
cc_input_flag = ""
makefile_flags = "PART="

api_paths = [
    "Microchip/PIC16F8x",
    "Microchip/xc8-generic",
    "Microchip/PIC16F-generic",
]

v_defines = [
]

inline_as_c_macro = true

string_default_len = 20

compiler_setup_path = "setup/xc8.toml"