# Project Name: Aixt, https =//github.com/fermarsan/aixt.git
#  Authors:
#    - Fernando M. Santa
#    - Camilo Gutierrez
#  Date: 2024
#  License: MIT
#
#  Description: Setup file for the Explorer16 (with PIC24)
#                port of Aixt project 
port =    "Raspberry-Pi-Pico"
board =   "Raspberry Pi Pico"
backend = "arduino"

cc_linux =   "arduino-cli"
cc_windows = "arduino-cli.exe"
cc_make_flags =   "compile -b arduino:mbed_rp2040:pico -v --output-dir @{file_dir_name}/build"

api_paths = [
    "Raspberry-Pi/Raspberry-Pi-Pico",
    "Arduino/arduino-generic",
]

v_defines = [
]

inline_as_c_macro = true

string_default_len = 50

compiler_setup_path = "setup/arduino32.toml"