# Project Name: Aixt, https =//github.com/fermarsan/aixt.git
# Authors:
#   - Camilo Gutierrez
#   - Fernando M. Santa
# Date: 2024
# License: MIT
#
# Description: This is the setup file for the Explorer16 (with PIC24)
#               port of Aixt project 
port =    "Raspberry-Pi-Pico"
board =   "Raspberry Pi Pico"
backend = "arduino"

cc_linux =   "arduino-cli"
cc_windows = "arduino-cli.exe"
cc_flags =   "compile -b arduino:avr:nano -v --output-dir ./build "
cc_output_flag = ""
cc_input_flag = ""
makefile_flags = ""

api_paths = [
    "Raspberry-Pi/Raspberry-Pi-Pico",
    "Arduino/Arduino-generic"
]

v_defines = [
]

inline_as_c_macro = false

string_default_len = 50

compiler_setup_path = "setup/arduino8.toml"